### ISSUE TITLE
Implementing the entities new in IFC4x1 specification

### ISSUE THREAD

**Issue by nsoonhui** [jmirtsch/GeometryGymIFC#11]
I'm aware that currently GeometryGym has included up to IFC4 specification.

Is it possible to include up to [IFC4x1](http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html/) too? In that way we can have more infrastructure entity definition such as [ifcAlignment](http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html/schema/ifcproductextension/lexical/ifcalignment.htm)

**Comment by jmirtsch** [comment]
Hi, 

I've been enabling IFC4x1 but only in the WorkInProgress branch at the moment.  You can find the latest commit here:
https://github.com/jmirtsch/GeometryGymIFC/blob/WorkInProgress/WorkInProgress/IfcAlignment/IFC%20Alignment.cs

Hope that helps,

Jon
