### ISSUE TITLE
No public constructor for IfcPipeSegmentType?

### ISSUE THREAD

**Issue by SS-TT** [jmirtsch/GeometryGymIFC#16]
Basically title.
All the constructors are `internal` and there's no builder method to create such an object.

How am I supposed to create one?

**Comment by jmirtsch** [comment]
Hi SS-TT,
Thanks for raising this issue.  The toolkit was originally developed as a closed source toolkit, and many constructors accessibility was not revised.  I have just pushed a commit to the Work in Progress branch with this improved.  If I've missed some then please raise them or make a pull request.
Thanks,

Jon

**Comment by SS-TT** [comment]
Thank you for the quick reponse!
I'll report back if I notice anything else.
