### ISSUE TITLE
elaboration

### ISSUE THREAD

**Issue by BKSpurgeon** [jmirtsch/GeometryGymIFC#2]
Hi

thank you for providing the code for viewing. i somehow randomly stumbled on this page.

Would you be able to elaborate what exactly it does?

> C# classes to generate and parse OpenBIM IFC (Industry Foundation Class) files

much appreciated. project looks quite interesting.

rgds

Ben

**Comment by TomH22** [comment]
Hi,

I work for a CAD-System (TheoCAD) and we work with C# 3.5. So I adapted it (in fast).

But the Ticket is now on pause. Ifc is very complicated and the task would take to long.

We have some Ifc-Exports, but …

I just keep that API in mind.

Best Regards

Tom Hennersdorf

Von: Ben Koshy [mailto:notifications@github.com]
Gesendet: Sonntag, 2. April 2017 05:23
An: jmirtsch/GeometryGymIFC <GeometryGymIFC@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [jmirtsch/GeometryGymIFC] elaboration (#2)


Hi

thank you for providing the code for viewing. i somehow randomly stumbled on this page.

Would you be able to elaborate what exactly it does?

C# classes to generate and parse OpenBIM IFC (Industry Foundation Class) files

much appreciated. project looks quite interesting.

rgds

Ben

**Comment by jmirtsch** [comment]
Hi Ben,

This c# project implements the Industry Foundation Class definition of object oriented representation of building and construction data.  https://en.wikipedia.org/wiki/Industry_Foundation_Classes
It provides read/write functionality in STEP, and also work in progress IfcJson and IfcXml expressions.

If you have any questions, please add further replies.


Hi Tom,  Did you see there was a second branch supporting dotnet3.5 ?  https://github.com/jmirtsch/GeometryGymIFC/tree/DotNet3.5  I haven't pushed recent changes to it yet though.

Cheers,

Jon

**Comment by TomH22** [comment]
Von: Jon Mirtschin [mailto:notifications@github.com]
Gesendet: Dienstag, 4. April 2017 08:29
An: jmirtsch/GeometryGymIFC <GeometryGymIFC@noreply.github.com>
Cc: TomH22 <tom.hennersdorf@hotmail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [jmirtsch/GeometryGymIFC] elaboration (#2)


Hi Ben,

This c# project implements the Industry Foundation Class definition of object oriented representation of building and construction data. https://en.wikipedia.org/wiki/Industry_Foundation_Classes
It provides read/write functionality in STEP, and also work in progress IfcJson and IfcXml expressions.

If you have any questions, please add further replies.

Hi Tom, Did you see there was a second branch supporting dotnet3.5 ?

no

https://github.com/jmirtsch/GeometryGymIFC/tree/DotNet3.5 I haven't pushed recent changes to it yet though.

Cheers,

Jon

**Comment by BKSpurgeon** [comment]
> It provides read/write functionality in STEP, and also work in progress IfcJson and IfcXml expression

Thank you for your reply. would you be able to elaborate on what STEP is?

rgds

Ben

**Comment by jmirtsch** [comment]
Hi Ben,

See if this reference helps:
https://en.wikipedia.org/wiki/ISO_10303-21

Cheers,

Jon

**Comment by BKSpurgeon** [comment]
Hi thx for the msg Mr Jon that link definitely helped.

I think I understand - to adopt a coding analogy:

- STEP = a way of representing data. (abstract)

- IFC = the specifics details of the general abstract skeletal structure of STEP - in terms of building and construction objects. (IFC can be thought of as a concrete implementation of the above STEP abstraction).
 
- Tekla/Revit/ArchiCAD data structures - IFC represents an abstraction of the specific data structures used by those tools - or in other words, the data structure Tekla etc. specifically uses is a concrete instance of IFC structure.
 
- This library allows one to programatically create data structures which can be read and manipulated by different software: e.g. Revit AND Tekla etc. (or any software which is IFC compatible).

Am I understanding this correctly?
