### ISSUE TITLE
IfcDoor with MappedRepresentation

### ISSUE THREAD

**Issue by TomH22** [jmirtsch/GeometryGymIFC#5]
Hello,

can one create a door with a MappedRepresentation or is this planed?

**Comment by jmirtsch** [comment]
You can find an example script generating an element with a mapped representation here:
https://github.com/BuildingSMART/IfcScript/blob/master/IfcScript/Examples/Bath.cs

Let me know if it doesn't help.

Cheers,

Jon

**Comment by TomH22** [comment]
thanks
